window.ENV = {
    FIREBASE_API_KEY: "VOTRE_API_KEY",
    FIREBASE_AUTH_DOMAIN: "VOTRE_AUTH_DOMAIN",
    FIREBASE_PROJECT_ID: "VOTRE_PROJECT_ID",
    FIREBASE_STORAGE_BUCKET: "VOTRE_STORAGE_BUCKET",
    FIREBASE_MESSAGING_SENDER_ID: "VOTRE_MESSAGING_SENDER_ID",
    FIREBASE_APP_ID: "VOTRE_APP_ID",
    FIREBASE_MEASUREMENT_ID: "VOTRE_MEASUREMENT_ID"
}; 